services:

  db:
    image: postgres:17.5
    env_file: ./auth_service/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service/
    env_file: ./auth_service/.env
    volumes:
      - ./auth_service/app:/app

volumes:
  pg_data: