services:

  db:
    image: postgres:17.5
    env_file: auth_service/dev.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: auth_service/.
    volumes:
      - /app:/auth_service/app

volumes:
  pg_data: